### ISSUE TITLE
Route Enhancer Pagination

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#138]
Hi,

I just try to complete my route enhancer for the pagination url:

`https://mydomain.de/events/calendar?tx_events2_events[%widget_0][currentPage]=2&cHash=b6706316b2ead1121901ce8d45e4eb57`
I tried this without success:

(...)
```
        routePath: '/page-{page}'
        _controller: 'Event::listSearchResults'
        _arguments:
          page: '@widget_0/currentPage'
```
(...)
```
    requirements:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
```

I guess that the controller is wrong.

Regards
Hobokens

**Comment by Schweriner** [comment]
Hey @Hobokens,

you will need another route for the default list view, because its controller is Day and the Action is list. Your mentioned route is only for the search results which has another controller.

```
-
        routePath: '/listpage-{page}'
        _controller: 'Day::list'
        _arguments:
          page: '@widget_0/currentPage'
```

**Comment by Hobokens** [comment]
@Schweriner - thanks for your advice.

**Comment by Hobokens** [comment]
Sorry, I missed your last comment to page 1.

**Comment by froemken** [comment]
Hello,

please use a configuration like that:

```
routeEnhancers:
  MapCategory:
    type: Simple
    routePath: '/cat/{category_id}'
    aspects:
      category_id:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: title
  Event:
    type: Extbase
    extension: Events2
    plugin: events
    routes:
      - routePath: '/first-page'
        _controller: 'Day::list'
      - routePath: '/page-{page}'
        _controller: 'Day::list'
        _arguments:
          page: '@widget_0/currentPage'
      - routePath: '//show/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
          date: timestamp
          event_title: event
    requirements:
      date: '\d+'
      event_title: '^[a-zA-Z0-9]+\-[0-9]+$'
    defaultController: 'Day::list'
    defaults:
      page: '0'
    aspects:
      date:
        type: TimestampMapper
        format: 'Y-m-d_Hi'
      event_title:
        type: PersistedPatternMapper
        tableName: 'tx_events2_domain_model_event'
        routeFieldPattern: '^(?P<title>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{title}-{uid}'
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
```

/first-page has to be before /page-{page}
