### ISSUE TITLE
English translation leads to double or triple instances in list

### ISSUE THREAD

**Issue by ja-sk** [jweiland-net/events2#179]
I am using Events2 5.0.0 with TYPO3 9.5.15

Addings events in the main language works fine. But as soon as I add a translation the list view shows the event twice in the chosen language.

So if I have an event in German, make an english translation the event shows twice in German in the german list and twice in english in the english list. 

If the event is not a single but a multi event it gets even weirder, sometimes showing three instances. But this behaviour is not consistent

**Comment by froemken** [comment]
Some problem as in your other ticket #180
Hopefully solved while upgrading to TYPO3 10

**Comment by froemken** [comment]
Found it. Since I have changed from Extbase Query to Doctrine Query the WHERE clause against sys_language_uid gets lost. Damn...that will need some time to repair.

**Comment by nessa4628** [comment]
Thank you for dedicating your time and energy into this! Really looking forward to the fixed version, because I would love to use this great extension.

**Comment by Hobokens** [comment]
Hi @froemken,

The behavior in my installation is a little different. When I add an English translation to a German event, I get the German event twice in the German list view, but the English event isn't listed in the English list view.
Regards
Hobokens

**Comment by derBoogie** [comment]
Hi @froemken 

because I urgently need events in multilanguage, I have added the sys_language_uid in DayRepository::findEvents as follows:

```
$context = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Context\Context::class);
$sys_language_uid = (int)$context->getPropertyFromAspect('language', 'id');
```

Line: 151: inserted after ->leftJoin(...)
```
->andWhere(	
  $queryBuilder->expr()->eq(
    'event.sys_language_uid',
    $queryBuilder->createNamedParameter($sys_language_uid, \PDO::PARAM_INT)
  )
)
```

Now the events are no longer listed more than once.

Regards, TJ

**Comment by froemken** [comment]
Hello @derBoogie 

thank you for your help. While upgrading our glossary2 I had the same problem and solved it with an OverlayHelper: https://github.com/jweiland-net/glossary2/blob/master/Classes/Helper/OverlayHelper.php

I'm sure it will made it into events2, too.

Have you seen that you can extend the query for events2 with EventListeners?
https://github.com/jweiland-net/events2/blob/master/Classes/Domain/Repository/DayRepository.php#L169-L171

Stefan

**Comment by derBoogie** [comment]
Hey @froemken 

thanks for the hints.

OverlayHelper looks good.

I have not worked with eventListeners before.
I will have a look at the concept in a quiet hour.

Regards
TJ

**Comment by derBoogie** [comment]
Hi @froemken,

here I'm again with this topic.

I have a page in TYPO3 11.5.38 with Events2 8.3.9.

My problem is that on the English events list page, all events are listed, even in German language, see: https://www.scheer-group.com/en/company/events/

There should be only one translated event visible "Data & Analytics Matchday – ScheerXperience SAP Arena".

Here is my language setting from config.yaml

```
languages:
  - title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
  - title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
```

Can you help?

Cheers, TJ
