### ISSUE TITLE
pageTitleProvider in event detail view not working

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#266]
On my website (TYPO3 10.4.16, events2 6.1.0) the pageTitleProvider is not working.

After some debugging, I found that the GET parameter "timestamp" is not found in table tx_events2_domain_model_day when passed to DayRepository::getDayRecord(). Therefore, I removed the day_time condition in the SQL query and added a ->groupBy('event'). With this, the output of the event title with date works. The question is, where does the wrong timestamp come from?

**Comment by froemken** [comment]
Hello @derBoogie 

in most cases an event can only be shown if a timestamp parameter exists in URL. This is needed to find the correct date in `tx_events2_domain_model_day` table. So, if GET parameter `timestamp` is not found, there is a problem in your URL or in the link generation of target page.
I just saw your ticket #267 where you have forgotten to set `timestamp` as GET parameter which could be the problem.

Nice greetings

Stefan

**Comment by derBoogie** [comment]
Hi @froemken 

thanks for the hint.

I found the Problem and solved it with a modification in config.yaml
Here the explanation:

GET-param `timestamp` is present and filled with a timestamp-value in Events2PageTitleProvider::getTitle() with the right event date but the **current time**, and this is wrong.

As a solution I added the start time to the date in event URL and now the timestamp of the event is found, and the title is generated correctly.

config.yaml:

```
routeEnhancers:
  Events2ShowPlugin:
    type: Extbase
    extension: Events2
    plugin: Events
    routes:
      -
        routePath: /
        _controller: 'Day::list'
      -
        routePath: '/kategorie/{category_title}'
        _controller: 'Event::listSearchResults'
        _arguments:
          category_title: search/mainCategory
      -
        routePath: '/seite-{page}'
        _controller: 'Day::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
          date: timestamp
          event_title: event
    requirements:
      date: '^\d{2,2}-\d{2,2}-\d{4,4}_\d{2,2}\.\d{2,2}$'
      event_title: '^[a-zA-Z0-9\-]+$'
      page: \d+
    defaultController: 'Day::list'
    aspects:
      date:
        type: TimestampMapper
        format: d-m-Y_H.i
      event_title:
        type: PersistedPatternMapper
        tableName: tx_events2_domain_model_event
        routeFieldName: path_segment
        routeFieldPattern: '^(?P<path_segment>.+)$'
        routeFieldResult: '{path_segment}'
      category_title:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
```

Greetings!
