### ISSUE TITLE
no speaking urls in sitamap.xml

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#267]
I can't get speaking urls in sitemap.xml to work (TYPO3 v10.4.16, Events2 v6.1.0).
The events are listet correctly in ...?sitemap=events&type=1533906435&cHash=...

TS-Setup:
```
plugin.tx_seo.config {
  xmlSitemap {
    sitemaps {
      events {
        provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
        config {
          table = tx_events2_domain_model_event
          sortField = tstamp
          lastModifiedField = tstamp
          pid = 112
          recursive = 1
          url {
            pageId = 113
            fieldToParameterMap {
              uid = tx_events2_event[event]
            }
            additionalGetParameters {
              tx_events2_event.controller = Day
              tx_events2_event.action = show
            }
            useCacheHash = 1
          }
        }
      }
    }
  }
}
```

config.yaml:
``` 
Events2ShowPlugin:
    type: Extbase
    extension: Events2
    plugin: Events
    routes:
      -
        routePath: /
        _controller: 'Day::list'
      -
        routePath: '/kategorie/{category_title}'
        _controller: 'Event::listSearchResults'
        _arguments:
          category_title: search/mainCategory
      -
        routePath: '/seite-{page}'
        _controller: 'Day::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
           date: timestamp
           event_title: event
    requirements:
      date: '^\d{2,2}-\d{2,2}-\d{4,4}_\d{2,2}\.\d{2,2}$'
      event_title: '^[a-zA-Z0-9\-]+$'
      page: '\d+'
    defaultController: 'Day::list'
    aspects:
      date:
        type: TimestampMapper
        format: 'd-m-Y_H.i'
      event_title:
        type: PersistedPatternMapper
        tableName: 'tx_events2_domain_model_event'
        routeFieldName: 'path_segment'
        routeFieldPattern: '^(?P<path_segment>.+)$'
        routeFieldResult: '{path_segment}'
      category_title:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
```
