### ISSUE TITLE
Routing of listSearchResults mainCategory

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#367]
Hi,
after the upate to v8.0.1 I don't get the route configured for the category search.

My category selector looks like:
```
<ul>
	<li class="label">Categories</li>				
	<f:for each="{selectorData.categories.main}" as="category" iteration="catIterator">				
	<li><a href="{f:uri.page(pageUid: '{data.pid}', additionalParams: '{no-cache: 1, tx_events2_events: {search: {mainCategory: \'{category.uid}\'}, controller: \'Search\', action: \'listSearchResults\'}}')}">{category.title}</a></li>
	</f:for>
</ul>
```

The Links always looks like:
```
https://mywebsite.de/events?no-cache=1&tx_events2_events[action]=listSearchResults&tx_events2_events[controller]=Search&tx_events2_events[search][mainCategory]=27&cHash=8204fd43e5a1924e78e4e2f11990bda6
```

My config.yaml
```
...
  Events2ShowPlugin:
    type: Extbase
    limitToPages:
      - 113
    extension: Events2
    plugin: Show
    routes:
      -
        routePath: '/{date}/{event_title}'
        _controller: 'Day::show'
        _arguments:
          date: timestamp
          event_title: event
    requirements:
      date: '^\d{2,2}-\d{2,2}-\d{4,4}_\d{2,2}\.\d{2,2}$'
      event_title: '^[a-zA-Z0-9\-]+$'
    defaultController: 'Day::show'
    aspects:
      date:
        type: TimestampMapper
        format: d-m-Y_H.i
      event_title:
        type: PersistedPatternMapper
        tableName: tx_events2_domain_model_event
        routeFieldName: path_segment
        routeFieldPattern: '^(?P<path_segment>.+)$'
        routeFieldResult: '{path_segment}'
  Events2ListPlugin:
    type: Extbase
    limitToPages:
      - 111
    extension: Events2
    plugin: List
    routes:
      -
        routePath: '/seite-{page}'
        _controller: 'Day::list'
        _arguments:
          page: 'currentPage'
    requirements:
      page: \d+
    defaultController: 'Day::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
  Events2SearchResultsPlugin:
    type: Extbase
    limitToPages:
      - 111
    extension: Events2
    plugin: SearchResults
    routes:
      -
        routePath: '/kategorie/{category_title}'
        _controller: 'Search::listSearchResults'
        _arguments:
          category_title: search/mainCategory
      -
        routePath: '/kategorie/{category_title}/seite-{page}'
        _controller: 'Search::listSearchResults'
        _arguments:
          category_title: search/mainCategory
          page: 'currentPage'
    requirements:
      page: \d+
    defaultController: 'Search::listSearchResults'
    aspects:
      category_title:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
...
```

What I'm doing wrong?
