### ISSUE TITLE
Alternative Times are not shown in translated record

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#371]
Hi,

I have a course that goes over 4 weeks each Monday through Friday. I configured it as `recurring event`,
In the German view all dates are displayed in the detail view. In the English view, however, they are not. The variable `{day.event.alternativeTimesIncludingRemovedGroupedAndSorted}` is empty. 

TYPO3 10.4.30, Events2 8.0.1

```
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
    solr_core_read: core_de
  -
    title: Englisch
    enabled: true
    languageId: 1
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
```
Regards
Hobokens
