### ISSUE TITLE
routing for search term

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/events2#399]
Hi,

can't get the routing for search term filter to work.
Search for categories is working fine.

What is wrong in my config?

```
Events2SearchResultsPlugin:
    type: Extbase
    limitToPages:
      - xxx
    extension: Events2
    plugin: SearchResults
    routes:
      - routePath: '/kategorie/{category_title}'
        _controller: 'Search::listSearchResults'
        _arguments:
          category_title: search/mainCategory
      - routePath: '/kategorie/{category_title}/seite-{page}'
        _controller: 'Search::listSearchResults'
        _arguments:
          category_title: search/mainCategory
          page: 'currentPage'
      - routePath: '/search/{search_term}'
        _controller: 'Search::listSearchResults'
        _arguments:
          search_term: search/search
    requirements:
      page: \d+
    defaultController: 'Search::listSearchResults'
    aspects:
      category_title:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
```
